(defun validate-hello (greetings)
  (cond ((search "hello" (string-downcase greetings)) t)
        ((search "ciao"  (string-downcase greetings)) t)
        ((search "salut" (string-downcase greetings)) t)
        ((search "hallo" (string-downcase greetings)) t)
        ((search "hola"  (string-downcase greetings)) t)
        ((search "ahoj"  (string-downcase greetings)) t)
        ((search "czesc" (string-downcase greetings)) t)
        (t nil)))
